# Generated by Django 5.2 on 2025-05-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
