# Generated by Django 5.2 on 2025-07-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_label_alter_label_id_labelproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.ManyToManyField(through='products.LabelProduct', to='products.label'),
        ),
    ]
