# Generated by Django 5.2 on 2025-07-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_allergy_ingredient_allergyingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(through='products.IngredientProduct', to='products.ingredient'),
        ),
    ]
