# Generated by Django 5.2 on 2025-07-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_allergy_ingredient_allergyingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allergy',
            field=models.ManyToManyField(through='products.AllergyIngredient', to='products.allergy'),
        ),
    ]
